###
# $Id$
###

###
# This directory:
###
PQE_TOP=`pwd`


all:
	cd src; $(MAKE) all

install:
	cd src; $(MAKE) install

uninstall:
	cd src; $(MAKE) uninstall

clean:
	cd src; $(MAKE) clean

clobber: clean


depends:
	cd src; $(MAKE) depends
