ERROR LOADING PROJECT FILES?
----------------------------
1. Don't panic.

2. On a command line, you need to run "qmake -recursive" from the ossim_qt4 top directory 
to generate these project files FIRST, then you can load this solution.

The qmake executable should be in your path with the %QT_HOME%\bin spec in your user 
env vars. Define QT_HOME as %OSSIM_DEPENDENCIES%\src\qt-4.5.1 (or whatever the latest is).

The project files generated by qmake may not work due to the template being used sets some attributes to bad values. You'll need to go through each item and verify the value OR use the hardcoded project files inside of ossim_qt4/src, apps/imagelinker and apps/iview. The solution file under svn control references these latter project files.

O.Kramer, Sep 2009