#ifndef ossimPlanetQtVersion_HEADER
#define ossimPlanetQtVersion_HEADER
#include <ossim/ossimVersion.h>
#define OSSIMPLANETQT_MAJOR_VERSION OSSIM_MAJOR_VERSION_NUMBER
#define OSSIMPLANETQT_MINOR_VERSION OSSIM_MINOR_VERSION_NUMBER
#define OSSIMPLANETQT_PATCH_VERSION OSSIM_RELEASE_NUMBER

#define OSSIMPLANETQT_BUILD_STRING ""


#endif
