###
# $Id: makefile.vc 10188 2007-01-04 16:02:37Z dburken $
#
# Windows nmake make file.
###
OSSIM_ROOT	=	..\..\..
!INCLUDE $(OSSIM_ROOT)\nmake.opt

OBJ = \
ossimIgen.obj \
ossimImageMpiMWriterSequenceConnection.obj \
ossimImageMpiSWriterSequenceConnection.obj \
ossimMpi.obj \
ossimMpiMasterOverviewSequencer.obj \
ossimMpiSlaveOverviewSequencer.obj \
ossimOrthoIgen.obj

default:	$(OBJ)

clean:
	$(RM) *.obj
