###
# $Id: Makefile 16352 2010-01-14 18:55:58Z bwatkins $
###

###
# Use make.opt to set things.
###
include make.opt

all:
	cd src; $(MAKE) all
	cd apps; $(MAKE) all

clean:
	cd src; $(MAKE) clean
	cd apps; $(MAKE) clean

depends:
	cd src; $(MAKE) depends
	cd apps; $(MAKE) depends

install:
	cd src; $(MAKE) install
	cd apps; $(MAKE) install

uninstall:
	cd src; $(MAKE) uninstall
	cd apps; $(MAKE) uninstall
