###
# $Id: Makefile 10395 2007-01-29 19:43:49Z dburken $
###

all:
	cd pqe; $(MAKE) all
	cd test; $(MAKE) all

clean:
	cd pqe; $(MAKE) clean
	cd test; $(MAKE) clean

depends:
	cd pqe; $(MAKE) depends
	cd test; $(MAKE) depends

install:
	cd pqe; $(MAKE) install
	cd test; $(MAKE) install

uninstall:
	cd pqe; $(MAKE) uninstall
	cd test; $(MAKE) uninstall

