default: 
	(cd Source; $(MAKE))
image_copy: 
	(cd Source; $(MAKE) image_copy)
	mv Source/image_copy bin/
image_open: 
	(cd Source; $(MAKE) image_open)
	mv Source/image_open bin/
image_data: 
	(cd Source; $(MAKE) image_data)
	mv Source/image_data bin/
