# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/sasha/.qgis/python/plugins/Qplanet/ui/datawork_ui.ui'
#
# Created: Wed Nov 25 23:57:51 2009
#      by: PyQt4 UI code generator 4.6.2-snapshot-20091115
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(355, 306)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/element-vector.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tab_7)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.ElevationGroupBox_2 = QtGui.QGroupBox(self.tab_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ElevationGroupBox_2.sizePolicy().hasHeightForWidth())
        self.ElevationGroupBox_2.setSizePolicy(sizePolicy)
        self.ElevationGroupBox_2.setObjectName("ElevationGroupBox_2")
        self.gridLayout_32 = QtGui.QGridLayout(self.ElevationGroupBox_2)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.InputElevlabel_2 = QtGui.QLabel(self.ElevationGroupBox_2)
        self.InputElevlabel_2.setObjectName("InputElevlabel_2")
        self.gridLayout_32.addWidget(self.InputElevlabel_2, 1, 2, 1, 1)
        self.Tilinglabel_2 = QtGui.QLabel(self.ElevationGroupBox_2)
        self.Tilinglabel_2.setObjectName("Tilinglabel_2")
        self.gridLayout_32.addWidget(self.Tilinglabel_2, 2, 2, 1, 1)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.InputRaster = QtGui.QComboBox(self.ElevationGroupBox_2)
        self.InputRaster.setObjectName("InputRaster")
        self.InputRaster.addItem("")
        self.InputRaster.setItemText(0, "")
        self.horizontalLayout_23.addWidget(self.InputRaster)
        self.gridLayout_32.addLayout(self.horizontalLayout_23, 1, 3, 1, 1)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem)
        self.Tile = QtGui.QLineEdit(self.ElevationGroupBox_2)
        self.Tile.setObjectName("Tile")
        self.horizontalLayout_24.addWidget(self.Tile)
        self.gridLayout_32.addLayout(self.horizontalLayout_24, 2, 3, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.ExportElev = QtGui.QPushButton(self.ElevationGroupBox_2)
        self.ExportElev.setObjectName("ExportElev")
        self.horizontalLayout_6.addWidget(self.ExportElev)
        self.gridLayout_32.addLayout(self.horizontalLayout_6, 4, 3, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Autotiling = QtGui.QRadioButton(self.ElevationGroupBox_2)
        self.Autotiling.setObjectName("Autotiling")
        self.horizontalLayout_9.addWidget(self.Autotiling)
        self.ManualTiling = QtGui.QRadioButton(self.ElevationGroupBox_2)
        self.ManualTiling.setObjectName("ManualTiling")
        self.horizontalLayout_9.addWidget(self.ManualTiling)
        self.gridLayout_32.addLayout(self.horizontalLayout_9, 0, 3, 1, 1)
        self.CopyElev = QtGui.QCheckBox(self.ElevationGroupBox_2)
        self.CopyElev.setObjectName("CopyElev")
        self.gridLayout_32.addWidget(self.CopyElev, 0, 2, 1, 1)
        self.verticalLayout_11.addWidget(self.ElevationGroupBox_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.tab_8)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.VectorGroupBox_2 = QtGui.QGroupBox(self.tab_8)
        self.VectorGroupBox_2.setObjectName("VectorGroupBox_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.VectorGroupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.InputVectorhorizontalLayout_2 = QtGui.QHBoxLayout()
        self.InputVectorhorizontalLayout_2.setObjectName("InputVectorhorizontalLayout_2")
        self.Point = QtGui.QRadioButton(self.VectorGroupBox_2)
        self.Point.setObjectName("Point")
        self.InputVectorhorizontalLayout_2.addWidget(self.Point)
        self.Line = QtGui.QRadioButton(self.VectorGroupBox_2)
        self.Line.setObjectName("Line")
        self.InputVectorhorizontalLayout_2.addWidget(self.Line)
        self.Polygon = QtGui.QRadioButton(self.VectorGroupBox_2)
        self.Polygon.setObjectName("Polygon")
        self.InputVectorhorizontalLayout_2.addWidget(self.Polygon)
        self.verticalLayout_3.addLayout(self.InputVectorhorizontalLayout_2)
        self.FeatureTypehorizontalLayout_2 = QtGui.QHBoxLayout()
        self.FeatureTypehorizontalLayout_2.setObjectName("FeatureTypehorizontalLayout_2")
        self.InputVector = QtGui.QComboBox(self.VectorGroupBox_2)
        self.InputVector.setObjectName("InputVector")
        self.InputVector.addItem("")
        self.InputVector.setItemText(0, "")
        self.FeatureTypehorizontalLayout_2.addWidget(self.InputVector)
        self.ExportVect = QtGui.QPushButton(self.VectorGroupBox_2)
        self.ExportVect.setObjectName("ExportVect")
        self.FeatureTypehorizontalLayout_2.addWidget(self.ExportVect)
        self.verticalLayout_3.addLayout(self.FeatureTypehorizontalLayout_2)
        self.scrollArea = QtGui.QScrollArea(self.VectorGroupBox_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 286, 573))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.KmlGeneralgroupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.KmlGeneralgroupBox.setObjectName("KmlGeneralgroupBox")
        self.gridLayout_29 = QtGui.QGridLayout(self.KmlGeneralgroupBox)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.Iconlabel = QtGui.QLabel(self.KmlGeneralgroupBox)
        self.Iconlabel.setObjectName("Iconlabel")
        self.gridLayout_29.addWidget(self.Iconlabel, 1, 0, 1, 1)
        self.LabelFieldlabel_2 = QtGui.QLabel(self.KmlGeneralgroupBox)
        self.LabelFieldlabel_2.setObjectName("LabelFieldlabel_2")
        self.gridLayout_29.addWidget(self.LabelFieldlabel_2, 2, 0, 1, 1)
        self.LineWidthlabel = QtGui.QLabel(self.KmlGeneralgroupBox)
        self.LineWidthlabel.setObjectName("LineWidthlabel")
        self.gridLayout_29.addWidget(self.LineWidthlabel, 3, 0, 1, 1)
        self.SelectIcon = QtGui.QComboBox(self.KmlGeneralgroupBox)
        self.SelectIcon.setObjectName("SelectIcon")
        self.SelectIcon.addItem("")
        self.SelectIcon.setItemText(0, "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/blue_circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SelectIcon.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/green_circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SelectIcon.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/red_circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SelectIcon.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/yellow_circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SelectIcon.addItem(icon4, "")
        self.gridLayout_29.addWidget(self.SelectIcon, 1, 1, 1, 1)
        self.AttributeList = QtGui.QComboBox(self.KmlGeneralgroupBox)
        self.AttributeList.setObjectName("AttributeList")
        self.gridLayout_29.addWidget(self.AttributeList, 2, 1, 1, 1)
        self.LineWidth = QtGui.QSpinBox(self.KmlGeneralgroupBox)
        self.LineWidth.setObjectName("LineWidth")
        self.gridLayout_29.addWidget(self.LineWidth, 3, 1, 1, 1)
        self.Tessellate = QtGui.QCheckBox(self.KmlGeneralgroupBox)
        self.Tessellate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Tessellate.setObjectName("Tessellate")
        self.gridLayout_29.addWidget(self.Tessellate, 4, 1, 1, 1)
        self.Tessellatelabel = QtGui.QLabel(self.KmlGeneralgroupBox)
        self.Tessellatelabel.setObjectName("Tessellatelabel")
        self.gridLayout_29.addWidget(self.Tessellatelabel, 4, 0, 1, 1)
        self.Extrude = QtGui.QCheckBox(self.KmlGeneralgroupBox)
        self.Extrude.setObjectName("Extrude")
        self.gridLayout_29.addWidget(self.Extrude, 5, 1, 1, 1)
        self.Extrudelabel = QtGui.QLabel(self.KmlGeneralgroupBox)
        self.Extrudelabel.setObjectName("Extrudelabel")
        self.gridLayout_29.addWidget(self.Extrudelabel, 5, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.KmlGeneralgroupBox)
        self.KmlColorgroupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.KmlColorgroupBox.setObjectName("KmlColorgroupBox")
        self.gridLayout_34 = QtGui.QGridLayout(self.KmlColorgroupBox)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.LabelColorhorizontalLayout = QtGui.QHBoxLayout()
        self.LabelColorhorizontalLayout.setObjectName("LabelColorhorizontalLayout")
        self.LabelColor = QtGui.QLineEdit(self.KmlColorgroupBox)
        self.LabelColor.setReadOnly(True)
        self.LabelColor.setObjectName("LabelColor")
        self.LabelColorhorizontalLayout.addWidget(self.LabelColor)
        self.LabelAlpha = QtGui.QSpinBox(self.KmlColorgroupBox)
        self.LabelAlpha.setMaximum(255)
        self.LabelAlpha.setProperty("value", 255)
        self.LabelAlpha.setObjectName("LabelAlpha")
        self.LabelColorhorizontalLayout.addWidget(self.LabelAlpha)
        self.gridLayout_34.addLayout(self.LabelColorhorizontalLayout, 1, 2, 1, 1)
        self.LineColorhorizontalLayout = QtGui.QHBoxLayout()
        self.LineColorhorizontalLayout.setObjectName("LineColorhorizontalLayout")
        self.LineColor = QtGui.QLineEdit(self.KmlColorgroupBox)
        self.LineColor.setReadOnly(True)
        self.LineColor.setObjectName("LineColor")
        self.LineColorhorizontalLayout.addWidget(self.LineColor)
        self.LineAlpha = QtGui.QSpinBox(self.KmlColorgroupBox)
        self.LineAlpha.setMaximum(255)
        self.LineAlpha.setProperty("value", 255)
        self.LineAlpha.setObjectName("LineAlpha")
        self.LineColorhorizontalLayout.addWidget(self.LineAlpha)
        self.gridLayout_34.addLayout(self.LineColorhorizontalLayout, 2, 2, 1, 1)
        self.PolyColorhorizontalLayout = QtGui.QHBoxLayout()
        self.PolyColorhorizontalLayout.setObjectName("PolyColorhorizontalLayout")
        self.PolyColor = QtGui.QLineEdit(self.KmlColorgroupBox)
        self.PolyColor.setReadOnly(True)
        self.PolyColor.setObjectName("PolyColor")
        self.PolyColorhorizontalLayout.addWidget(self.PolyColor)
        self.PolygonAlpha = QtGui.QSpinBox(self.KmlColorgroupBox)
        self.PolygonAlpha.setMaximum(255)
        self.PolygonAlpha.setProperty("value", 255)
        self.PolygonAlpha.setObjectName("PolygonAlpha")
        self.PolyColorhorizontalLayout.addWidget(self.PolygonAlpha)
        self.gridLayout_34.addLayout(self.PolyColorhorizontalLayout, 3, 2, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.colorModeEnum = QtGui.QComboBox(self.KmlColorgroupBox)
        self.colorModeEnum.setObjectName("colorModeEnum")
        self.colorModeEnum.addItem("")
        self.colorModeEnum.setItemText(0, "")
        self.colorModeEnum.addItem("")
        self.colorModeEnum.addItem("")
        self.horizontalLayout.addWidget(self.colorModeEnum)
        self.gridLayout_34.addLayout(self.horizontalLayout, 0, 2, 1, 1)
        self.VectorPolygonColor = QtGui.QToolButton(self.KmlColorgroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VectorPolygonColor.sizePolicy().hasHeightForWidth())
        self.VectorPolygonColor.setSizePolicy(sizePolicy)
        self.VectorPolygonColor.setObjectName("VectorPolygonColor")
        self.gridLayout_34.addWidget(self.VectorPolygonColor, 3, 0, 1, 1)
        self.VectorLineColor = QtGui.QToolButton(self.KmlColorgroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VectorLineColor.sizePolicy().hasHeightForWidth())
        self.VectorLineColor.setSizePolicy(sizePolicy)
        self.VectorLineColor.setAcceptDrops(False)
        self.VectorLineColor.setAutoFillBackground(False)
        self.VectorLineColor.setAutoRaise(False)
        self.VectorLineColor.setObjectName("VectorLineColor")
        self.gridLayout_34.addWidget(self.VectorLineColor, 2, 0, 1, 1)
        self.VectorLabelColor = QtGui.QToolButton(self.KmlColorgroupBox)
        self.VectorLabelColor.setObjectName("VectorLabelColor")
        self.gridLayout_34.addWidget(self.VectorLabelColor, 1, 0, 1, 1)
        self.ColorModelabel_2 = QtGui.QLabel(self.KmlColorgroupBox)
        self.ColorModelabel_2.setObjectName("ColorModelabel_2")
        self.gridLayout_34.addWidget(self.ColorModelabel_2, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.KmlColorgroupBox)
        self.KmlElevationgroupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.KmlElevationgroupBox_2.setObjectName("KmlElevationgroupBox_2")
        self.gridLayout_33 = QtGui.QGridLayout(self.KmlElevationgroupBox_2)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.Offsetlabel_2 = QtGui.QLabel(self.KmlElevationgroupBox_2)
        self.Offsetlabel_2.setObjectName("Offsetlabel_2")
        self.horizontalLayout_10.addWidget(self.Offsetlabel_2)
        self.Offset = QtGui.QDoubleSpinBox(self.KmlElevationgroupBox_2)
        self.Offset.setObjectName("Offset")
        self.horizontalLayout_10.addWidget(self.Offset)
        self.gridLayout_33.addLayout(self.horizontalLayout_10, 7, 0, 1, 1)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.HeightFieldlabel_2 = QtGui.QLabel(self.KmlElevationgroupBox_2)
        self.HeightFieldlabel_2.setObjectName("HeightFieldlabel_2")
        self.horizontalLayout_25.addWidget(self.HeightFieldlabel_2)
        self.HeightColumn = QtGui.QComboBox(self.KmlElevationgroupBox_2)
        self.HeightColumn.setObjectName("HeightColumn")
        self.horizontalLayout_25.addWidget(self.HeightColumn)
        self.gridLayout_33.addLayout(self.horizontalLayout_25, 5, 0, 1, 1)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.Heightlabel_2 = QtGui.QLabel(self.KmlElevationgroupBox_2)
        self.Heightlabel_2.setObjectName("Heightlabel_2")
        self.horizontalLayout_26.addWidget(self.Heightlabel_2)
        self.ExtrudeType = QtGui.QComboBox(self.KmlElevationgroupBox_2)
        self.ExtrudeType.setObjectName("ExtrudeType")
        self.ExtrudeType.addItem("")
        self.ExtrudeType.setItemText(0, "")
        self.ExtrudeType.addItem("")
        self.ExtrudeType.addItem("")
        self.ExtrudeType.addItem("")
        self.ExtrudeType.addItem("")
        self.horizontalLayout_26.addWidget(self.ExtrudeType)
        self.gridLayout_33.addLayout(self.horizontalLayout_26, 3, 0, 1, 1)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.AltitudeModelabel_2 = QtGui.QLabel(self.KmlElevationgroupBox_2)
        self.AltitudeModelabel_2.setObjectName("AltitudeModelabel_2")
        self.horizontalLayout_27.addWidget(self.AltitudeModelabel_2)
        self.AltitudeMode = QtGui.QComboBox(self.KmlElevationgroupBox_2)
        self.AltitudeMode.setObjectName("AltitudeMode")
        self.AltitudeMode.addItem("")
        self.AltitudeMode.setItemText(0, "")
        self.AltitudeMode.addItem("")
        self.AltitudeMode.addItem("")
        self.AltitudeMode.addItem("")
        self.horizontalLayout_27.addWidget(self.AltitudeMode)
        self.gridLayout_33.addLayout(self.horizontalLayout_27, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.KmlElevationgroupBox_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout_12.addWidget(self.VectorGroupBox_2)
        self.tabWidget.addTab(self.tab_8, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.update = QtGui.QPushButton(Form)
        self.update.setObjectName("update")
        self.horizontalLayout_8.addWidget(self.update)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_8)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Kml view-save", None, QtGui.QApplication.UnicodeUTF8))
        self.InputElevlabel_2.setText(QtGui.QApplication.translate("Form", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.Tilinglabel_2.setText(QtGui.QApplication.translate("Form", "Tiling", None, QtGui.QApplication.UnicodeUTF8))
        self.ExportElev.setText(QtGui.QApplication.translate("Form", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.Autotiling.setText(QtGui.QApplication.translate("Form", "AutoTiling", None, QtGui.QApplication.UnicodeUTF8))
        self.ManualTiling.setText(QtGui.QApplication.translate("Form", "ManualTiling", None, QtGui.QApplication.UnicodeUTF8))
        self.CopyElev.setText(QtGui.QApplication.translate("Form", "cp", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QtGui.QApplication.translate("Form", "Elevation", None, QtGui.QApplication.UnicodeUTF8))
        self.Point.setText(QtGui.QApplication.translate("Form", "Point", None, QtGui.QApplication.UnicodeUTF8))
        self.Line.setText(QtGui.QApplication.translate("Form", "Line", None, QtGui.QApplication.UnicodeUTF8))
        self.Polygon.setText(QtGui.QApplication.translate("Form", "Polygon", None, QtGui.QApplication.UnicodeUTF8))
        self.ExportVect.setText(QtGui.QApplication.translate("Form", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.KmlGeneralgroupBox.setTitle(QtGui.QApplication.translate("Form", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.Iconlabel.setText(QtGui.QApplication.translate("Form", "Icon", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelFieldlabel_2.setText(QtGui.QApplication.translate("Form", "LabelField", None, QtGui.QApplication.UnicodeUTF8))
        self.LineWidthlabel.setText(QtGui.QApplication.translate("Form", "Line Width", None, QtGui.QApplication.UnicodeUTF8))
        self.SelectIcon.setItemText(1, QtGui.QApplication.translate("Form", "blue_circle", None, QtGui.QApplication.UnicodeUTF8))
        self.SelectIcon.setItemText(2, QtGui.QApplication.translate("Form", "green_circle", None, QtGui.QApplication.UnicodeUTF8))
        self.SelectIcon.setItemText(3, QtGui.QApplication.translate("Form", "red_circle", None, QtGui.QApplication.UnicodeUTF8))
        self.SelectIcon.setItemText(4, QtGui.QApplication.translate("Form", "yellow_circle", None, QtGui.QApplication.UnicodeUTF8))
        self.Tessellatelabel.setText(QtGui.QApplication.translate("Form", "Tessellate", None, QtGui.QApplication.UnicodeUTF8))
        self.Extrudelabel.setText(QtGui.QApplication.translate("Form", "Extrude", None, QtGui.QApplication.UnicodeUTF8))
        self.KmlColorgroupBox.setTitle(QtGui.QApplication.translate("Form", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.colorModeEnum.setItemText(1, QtGui.QApplication.translate("Form", "normal", None, QtGui.QApplication.UnicodeUTF8))
        self.colorModeEnum.setItemText(2, QtGui.QApplication.translate("Form", "random", None, QtGui.QApplication.UnicodeUTF8))
        self.VectorPolygonColor.setText(QtGui.QApplication.translate("Form", "Polygon", None, QtGui.QApplication.UnicodeUTF8))
        self.VectorLineColor.setText(QtGui.QApplication.translate("Form", "Line", None, QtGui.QApplication.UnicodeUTF8))
        self.VectorLabelColor.setText(QtGui.QApplication.translate("Form", "Label", None, QtGui.QApplication.UnicodeUTF8))
        self.ColorModelabel_2.setText(QtGui.QApplication.translate("Form", "ColorMode", None, QtGui.QApplication.UnicodeUTF8))
        self.KmlElevationgroupBox_2.setTitle(QtGui.QApplication.translate("Form", "Elevation", None, QtGui.QApplication.UnicodeUTF8))
        self.Offsetlabel_2.setText(QtGui.QApplication.translate("Form", "OffSet", None, QtGui.QApplication.UnicodeUTF8))
        self.HeightFieldlabel_2.setText(QtGui.QApplication.translate("Form", "HeightField", None, QtGui.QApplication.UnicodeUTF8))
        self.Heightlabel_2.setText(QtGui.QApplication.translate("Form", "Heigth", None, QtGui.QApplication.UnicodeUTF8))
        self.ExtrudeType.setItemText(1, QtGui.QApplication.translate("Form", "2D", None, QtGui.QApplication.UnicodeUTF8))
        self.ExtrudeType.setItemText(2, QtGui.QApplication.translate("Form", "3D", None, QtGui.QApplication.UnicodeUTF8))
        self.ExtrudeType.setItemText(3, QtGui.QApplication.translate("Form", "Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.ExtrudeType.setItemText(4, QtGui.QApplication.translate("Form", "Attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.AltitudeModelabel_2.setText(QtGui.QApplication.translate("Form", "Altitude   ", None, QtGui.QApplication.UnicodeUTF8))
        self.AltitudeMode.setItemText(1, QtGui.QApplication.translate("Form", "clampToGround", None, QtGui.QApplication.UnicodeUTF8))
        self.AltitudeMode.setItemText(2, QtGui.QApplication.translate("Form", "relativeToGround", None, QtGui.QApplication.UnicodeUTF8))
        self.AltitudeMode.setItemText(3, QtGui.QApplication.translate("Form", "absolute", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), QtGui.QApplication.translate("Form", "KML", None, QtGui.QApplication.UnicodeUTF8))
        self.update.setText(QtGui.QApplication.translate("Form", "Refresh", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
