# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/sasha/.qgis/python/plugins/Qplanet/ui/kmlsave_ui.ui'
#
# Created: Tue Nov 24 21:54:36 2009
#      by: PyQt4 UI code generator 4.6.2-snapshot-20091115
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(340, 336)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/element-vector.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtGui.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 297, 664))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.KmlGeneralgroupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.KmlGeneralgroupBox.setObjectName("KmlGeneralgroupBox")
        self.gridLayout = QtGui.QGridLayout(self.KmlGeneralgroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Extrudelabel = QtGui.QLabel(self.KmlGeneralgroupBox)
        self.Extrudelabel.setObjectName("Extrudelabel")
        self.horizontalLayout_4.addWidget(self.Extrudelabel)
        self.Extrude = QtGui.QCheckBox(self.KmlGeneralgroupBox)
        self.Extrude.setObjectName("Extrude")
        self.horizontalLayout_4.addWidget(self.Extrude)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.Offset = QtGui.QDoubleSpinBox(self.KmlGeneralgroupBox)
        self.Offset.setObjectName("Offset")
        self.horizontalLayout_4.addWidget(self.Offset)
        self.gridLayout.addLayout(self.horizontalLayout_4, 7, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Tessellatelabel = QtGui.QLabel(self.KmlGeneralgroupBox)
        self.Tessellatelabel.setObjectName("Tessellatelabel")
        self.horizontalLayout_6.addWidget(self.Tessellatelabel)
        self.Tessellate = QtGui.QCheckBox(self.KmlGeneralgroupBox)
        self.Tessellate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Tessellate.setObjectName("Tessellate")
        self.horizontalLayout_6.addWidget(self.Tessellate)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_6, 8, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 7, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 6, 1, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.LineWidthlabel = QtGui.QLabel(self.KmlGeneralgroupBox)
        self.LineWidthlabel.setObjectName("LineWidthlabel")
        self.horizontalLayout_9.addWidget(self.LineWidthlabel)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.LineWidth = QtGui.QSpinBox(self.KmlGeneralgroupBox)
        self.LineWidth.setObjectName("LineWidth")
        self.horizontalLayout_9.addWidget(self.LineWidth)
        self.gridLayout.addLayout(self.horizontalLayout_9, 6, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 3, 1, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.Iconlabel = QtGui.QLabel(self.KmlGeneralgroupBox)
        self.Iconlabel.setObjectName("Iconlabel")
        self.horizontalLayout_10.addWidget(self.Iconlabel)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.SelectIcon = QtGui.QComboBox(self.KmlGeneralgroupBox)
        self.SelectIcon.setObjectName("SelectIcon")
        self.SelectIcon.addItem("")
        self.SelectIcon.setItemText(0, "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/blue_circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SelectIcon.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/green_circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SelectIcon.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/red_circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SelectIcon.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/yellow_circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SelectIcon.addItem(icon4, "")
        self.horizontalLayout_10.addWidget(self.SelectIcon)
        self.gridLayout.addLayout(self.horizontalLayout_10, 3, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 8, 1, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 2, 1, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.KmlGeneralgroupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.kmllabel = QtGui.QLineEdit(self.KmlGeneralgroupBox)
        self.kmllabel.setObjectName("kmllabel")
        self.horizontalLayout_2.addWidget(self.kmllabel)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.KmlGeneralgroupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        self.kmlname = QtGui.QLineEdit(self.KmlGeneralgroupBox)
        self.kmlname.setObjectName("kmlname")
        self.horizontalLayout.addWidget(self.kmlname)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.KmlGeneralgroupBox)
        self.KmlColorgroupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.KmlColorgroupBox.setObjectName("KmlColorgroupBox")
        self.gridLayout_29 = QtGui.QGridLayout(self.KmlColorgroupBox)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.LabelColorhorizontalLayout = QtGui.QHBoxLayout()
        self.LabelColorhorizontalLayout.setObjectName("LabelColorhorizontalLayout")
        self.labelcolorlabel = QtGui.QLineEdit(self.KmlColorgroupBox)
        self.labelcolorlabel.setReadOnly(True)
        self.labelcolorlabel.setObjectName("labelcolorlabel")
        self.LabelColorhorizontalLayout.addWidget(self.labelcolorlabel)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.LabelColorhorizontalLayout.addItem(spacerItem13)
        self.LabelAlpha = QtGui.QSpinBox(self.KmlColorgroupBox)
        self.LabelAlpha.setMaximum(255)
        self.LabelAlpha.setProperty("value", 255)
        self.LabelAlpha.setObjectName("LabelAlpha")
        self.LabelColorhorizontalLayout.addWidget(self.LabelAlpha)
        self.gridLayout_29.addLayout(self.LabelColorhorizontalLayout, 0, 2, 1, 1)
        self.LineColorhorizontalLayout = QtGui.QHBoxLayout()
        self.LineColorhorizontalLayout.setObjectName("LineColorhorizontalLayout")
        self.linecolorlabel = QtGui.QLineEdit(self.KmlColorgroupBox)
        self.linecolorlabel.setReadOnly(True)
        self.linecolorlabel.setObjectName("linecolorlabel")
        self.LineColorhorizontalLayout.addWidget(self.linecolorlabel)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.LineColorhorizontalLayout.addItem(spacerItem14)
        self.LineAlpha = QtGui.QSpinBox(self.KmlColorgroupBox)
        self.LineAlpha.setMaximum(255)
        self.LineAlpha.setProperty("value", 255)
        self.LineAlpha.setObjectName("LineAlpha")
        self.LineColorhorizontalLayout.addWidget(self.LineAlpha)
        self.gridLayout_29.addLayout(self.LineColorhorizontalLayout, 1, 2, 1, 1)
        self.PolyColorhorizontalLayout = QtGui.QHBoxLayout()
        self.PolyColorhorizontalLayout.setObjectName("PolyColorhorizontalLayout")
        self.polygoncolorlabel = QtGui.QLineEdit(self.KmlColorgroupBox)
        self.polygoncolorlabel.setReadOnly(True)
        self.polygoncolorlabel.setObjectName("polygoncolorlabel")
        self.PolyColorhorizontalLayout.addWidget(self.polygoncolorlabel)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.PolyColorhorizontalLayout.addItem(spacerItem15)
        self.PolygonAlpha = QtGui.QSpinBox(self.KmlColorgroupBox)
        self.PolygonAlpha.setMaximum(255)
        self.PolygonAlpha.setProperty("value", 255)
        self.PolygonAlpha.setObjectName("PolygonAlpha")
        self.PolyColorhorizontalLayout.addWidget(self.PolygonAlpha)
        self.gridLayout_29.addLayout(self.PolyColorhorizontalLayout, 2, 2, 1, 1)
        self.polygoncolor = QtGui.QToolButton(self.KmlColorgroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.polygoncolor.sizePolicy().hasHeightForWidth())
        self.polygoncolor.setSizePolicy(sizePolicy)
        self.polygoncolor.setObjectName("polygoncolor")
        self.gridLayout_29.addWidget(self.polygoncolor, 2, 0, 1, 1)
        self.linecolor = QtGui.QToolButton(self.KmlColorgroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linecolor.sizePolicy().hasHeightForWidth())
        self.linecolor.setSizePolicy(sizePolicy)
        self.linecolor.setAcceptDrops(False)
        self.linecolor.setAutoFillBackground(False)
        self.linecolor.setAutoRaise(False)
        self.linecolor.setObjectName("linecolor")
        self.gridLayout_29.addWidget(self.linecolor, 1, 0, 1, 1)
        self.labelcolor = QtGui.QToolButton(self.KmlColorgroupBox)
        self.labelcolor.setObjectName("labelcolor")
        self.gridLayout_29.addWidget(self.labelcolor, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.KmlColorgroupBox)
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.longitude = QtGui.QLineEdit(self.groupBox)
        self.longitude.setObjectName("longitude")
        self.horizontalLayout_3.addWidget(self.longitude)
        self.latitude = QtGui.QLineEdit(self.groupBox)
        self.latitude.setObjectName("latitude")
        self.horizontalLayout_3.addWidget(self.latitude)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Zoom = QtGui.QLineEdit(self.groupBox)
        self.Zoom.setObjectName("Zoom")
        self.horizontalLayout_5.addWidget(self.Zoom)
        self.Range = QtGui.QLineEdit(self.groupBox)
        self.Range.setObjectName("Range")
        self.horizontalLayout_5.addWidget(self.Range)
        self.Roll = QtGui.QLineEdit(self.groupBox)
        self.Roll.setObjectName("Roll")
        self.horizontalLayout_5.addWidget(self.Roll)
        self.Pitch = QtGui.QLineEdit(self.groupBox)
        self.Pitch.setObjectName("Pitch")
        self.horizontalLayout_5.addWidget(self.Pitch)
        self.Head = QtGui.QLineEdit(self.groupBox)
        self.Head.setObjectName("Head")
        self.horizontalLayout_5.addWidget(self.Head)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.description = QtGui.QTextEdit(self.groupBox_2)
        self.description.setObjectName("description")
        self.verticalLayout.addWidget(self.description)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.update = QtGui.QPushButton(Form)
        self.update.setObjectName("update")
        self.horizontalLayout_8.addWidget(self.update)
        self.openDir = QtGui.QPushButton(Form)
        self.openDir.setObjectName("openDir")
        self.horizontalLayout_8.addWidget(self.openDir)
        self.save = QtGui.QPushButton(Form)
        self.save.setObjectName("save")
        self.horizontalLayout_8.addWidget(self.save)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Kml view-save", None, QtGui.QApplication.UnicodeUTF8))
        self.KmlGeneralgroupBox.setTitle(QtGui.QApplication.translate("Form", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.Extrudelabel.setText(QtGui.QApplication.translate("Form", "Extrude", None, QtGui.QApplication.UnicodeUTF8))
        self.Tessellatelabel.setText(QtGui.QApplication.translate("Form", "Tessellate", None, QtGui.QApplication.UnicodeUTF8))
        self.LineWidthlabel.setText(QtGui.QApplication.translate("Form", "Line Width", None, QtGui.QApplication.UnicodeUTF8))
        self.Iconlabel.setText(QtGui.QApplication.translate("Form", "Icon", None, QtGui.QApplication.UnicodeUTF8))
        self.SelectIcon.setItemText(1, QtGui.QApplication.translate("Form", "blue_circle", None, QtGui.QApplication.UnicodeUTF8))
        self.SelectIcon.setItemText(2, QtGui.QApplication.translate("Form", "green_circle", None, QtGui.QApplication.UnicodeUTF8))
        self.SelectIcon.setItemText(3, QtGui.QApplication.translate("Form", "red_circle", None, QtGui.QApplication.UnicodeUTF8))
        self.SelectIcon.setItemText(4, QtGui.QApplication.translate("Form", "yellow_circle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Label", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.KmlColorgroupBox.setTitle(QtGui.QApplication.translate("Form", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.polygoncolor.setText(QtGui.QApplication.translate("Form", "Polygon", None, QtGui.QApplication.UnicodeUTF8))
        self.linecolor.setText(QtGui.QApplication.translate("Form", "Line", None, QtGui.QApplication.UnicodeUTF8))
        self.labelcolor.setText(QtGui.QApplication.translate("Form", "Label", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.update.setText(QtGui.QApplication.translate("Form", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.openDir.setText(QtGui.QApplication.translate("Form", "Open Dir", None, QtGui.QApplication.UnicodeUTF8))
        self.save.setText(QtGui.QApplication.translate("Form", "Save", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
