# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/sasha/.qgis/python/plugins/Qplanet/ui/QPlanetSasha_ui.ui'
#
# Created: Tue Nov 24 21:55:43 2009
#      by: PyQt4 UI code generator 4.6.2-snapshot-20091115
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_OssimPlanetSasha(object):
    def setupUi(self, OssimPlanetSasha):
        OssimPlanetSasha.setObjectName("OssimPlanetSasha")
        OssimPlanetSasha.resize(642, 267)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/epi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        OssimPlanetSasha.setWindowIcon(icon)
        OssimPlanetSasha.setDocumentMode(False)
        OssimPlanetSasha.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(OssimPlanetSasha)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.PanGroupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PanGroupBox.sizePolicy().hasHeightForWidth())
        self.PanGroupBox.setSizePolicy(sizePolicy)
        self.PanGroupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.PanGroupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.PanGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.PanGroupBox.setObjectName("PanGroupBox")
        self.gridLayout_5 = QtGui.QGridLayout(self.PanGroupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.northwest = QtGui.QToolButton(self.PanGroupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/shapeimage_9.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.northwest.setIcon(icon1)
        self.northwest.setObjectName("northwest")
        self.gridLayout_5.addWidget(self.northwest, 1, 5, 1, 1)
        self.north = QtGui.QToolButton(self.PanGroupBox)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/shapeimage_3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.north.setIcon(icon2)
        self.north.setObjectName("north")
        self.gridLayout_5.addWidget(self.north, 1, 2, 1, 1)
        self.northeast = QtGui.QToolButton(self.PanGroupBox)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/shapeimage_7.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.northeast.setIcon(icon3)
        self.northeast.setObjectName("northeast")
        self.gridLayout_5.addWidget(self.northeast, 1, 0, 1, 1)
        self.west = QtGui.QToolButton(self.PanGroupBox)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/shapeimage_5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.west.setIcon(icon4)
        self.west.setObjectName("west")
        self.gridLayout_5.addWidget(self.west, 2, 5, 1, 1)
        self.center = QtGui.QToolButton(self.PanGroupBox)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/pan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.center.setIcon(icon5)
        self.center.setObjectName("center")
        self.gridLayout_5.addWidget(self.center, 2, 2, 1, 1)
        self.east = QtGui.QToolButton(self.PanGroupBox)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/shapeimage_4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.east.setIcon(icon6)
        self.east.setObjectName("east")
        self.gridLayout_5.addWidget(self.east, 2, 0, 1, 1)
        self.southwest = QtGui.QToolButton(self.PanGroupBox)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/shapeimage_8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.southwest.setIcon(icon7)
        self.southwest.setObjectName("southwest")
        self.gridLayout_5.addWidget(self.southwest, 3, 5, 1, 1)
        self.south = QtGui.QToolButton(self.PanGroupBox)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/shapeimage_6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.south.setIcon(icon8)
        self.south.setObjectName("south")
        self.gridLayout_5.addWidget(self.south, 3, 2, 1, 1)
        self.southeast = QtGui.QToolButton(self.PanGroupBox)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/shapeimage_10.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.southeast.setIcon(icon9)
        self.southeast.setObjectName("southeast")
        self.gridLayout_5.addWidget(self.southeast, 3, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.PanGroupBox)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea_3 = QtGui.QScrollArea(self.tab_2)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtGui.QWidget(self.scrollArea_3)
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 407, 229))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Lat = QtGui.QLineEdit(self.scrollAreaWidgetContents_3)
        self.Lat.setAlignment(QtCore.Qt.AlignCenter)
        self.Lat.setObjectName("Lat")
        self.horizontalLayout_5.addWidget(self.Lat)
        self.Lon = QtGui.QLineEdit(self.scrollAreaWidgetContents_3)
        self.Lon.setAlignment(QtCore.Qt.AlignCenter)
        self.Lon.setObjectName("Lon")
        self.horizontalLayout_5.addWidget(self.Lon)
        self.SendPosition = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        self.SendPosition.setObjectName("SendPosition")
        self.horizontalLayout_5.addWidget(self.SendPosition)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.line_5 = QtGui.QFrame(self.scrollAreaWidgetContents_3)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_4.addWidget(self.line_5)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.Nord = QtGui.QLineEdit(self.scrollAreaWidgetContents_3)
        self.Nord.setObjectName("Nord")
        self.horizontalLayout_10.addWidget(self.Nord)
        self.East = QtGui.QLineEdit(self.scrollAreaWidgetContents_3)
        self.East.setObjectName("East")
        self.horizontalLayout_10.addWidget(self.East)
        self.utmcode = QtGui.QLineEdit(self.scrollAreaWidgetContents_3)
        self.utmcode.setMinimumSize(QtCore.QSize(30, 0))
        self.utmcode.setMaximumSize(QtCore.QSize(35, 16777215))
        self.utmcode.setObjectName("utmcode")
        self.horizontalLayout_10.addWidget(self.utmcode)
        self.ellipse = QtGui.QComboBox(self.scrollAreaWidgetContents_3)
        self.ellipse.setMaximumSize(QtCore.QSize(150, 26))
        self.ellipse.setObjectName("ellipse")
        self.ellipse.addItem("")
        self.ellipse.addItem("")
        self.ellipse.addItem("")
        self.ellipse.addItem("")
        self.ellipse.addItem("")
        self.ellipse.addItem("")
        self.ellipse.addItem("")
        self.ellipse.addItem("")
        self.ellipse.addItem("")
        self.ellipse.addItem("")
        self.ellipse.addItem("")
        self.ellipse.addItem("")
        self.ellipse.addItem("")
        self.ellipse.addItem("")
        self.ellipse.addItem("")
        self.ellipse.addItem("")
        self.ellipse.addItem("")
        self.ellipse.addItem("")
        self.ellipse.addItem("")
        self.ellipse.addItem("")
        self.ellipse.addItem("")
        self.ellipse.addItem("")
        self.ellipse.addItem("")
        self.ellipse.addItem("")
        self.horizontalLayout_10.addWidget(self.ellipse)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.line_6 = QtGui.QFrame(self.scrollAreaWidgetContents_3)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_4.addWidget(self.line_6)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.addqlayer = QtGui.QToolButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.addqlayer.setFont(font)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/element-cell.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addqlayer.setIcon(icon10)
        self.addqlayer.setObjectName("addqlayer")
        self.horizontalLayout_14.addWidget(self.addqlayer)
        self.removeqlayer = QtGui.QToolButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.removeqlayer.setFont(font)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/element-cell-delete.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeqlayer.setIcon(icon11)
        self.removeqlayer.setObjectName("removeqlayer")
        self.horizontalLayout_14.addWidget(self.removeqlayer)
        self.qgislayer = QtGui.QComboBox(self.scrollAreaWidgetContents_3)
        self.qgislayer.setObjectName("qgislayer")
        self.horizontalLayout_14.addWidget(self.qgislayer)
        self.addVlayer = QtGui.QToolButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.addVlayer.setFont(font)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/element-vector.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addVlayer.setIcon(icon12)
        self.addVlayer.setObjectName("addVlayer")
        self.horizontalLayout_14.addWidget(self.addVlayer)
        self.removeVlayer = QtGui.QToolButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.removeVlayer.setFont(font)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/element-vector-remove.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeVlayer.setIcon(icon13)
        self.removeVlayer.setObjectName("removeVlayer")
        self.horizontalLayout_14.addWidget(self.removeVlayer)
        self.qgisVlayer = QtGui.QComboBox(self.scrollAreaWidgetContents_3)
        self.qgisVlayer.setObjectName("qgisVlayer")
        self.horizontalLayout_14.addWidget(self.qgisVlayer)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.line_7 = QtGui.QFrame(self.scrollAreaWidgetContents_3)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_4.addWidget(self.line_7)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Place = QtGui.QComboBox(self.scrollAreaWidgetContents_3)
        self.Place.setObjectName("Place")
        self.Place.addItem("")
        self.Place.setItemText(0, "")
        self.horizontalLayout_2.addWidget(self.Place)
        self.placezone = QtGui.QComboBox(self.scrollAreaWidgetContents_3)
        self.placezone.setObjectName("placezone")
        self.horizontalLayout_2.addWidget(self.placezone)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_2.addWidget(self.scrollArea_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea_4 = QtGui.QScrollArea(self.tab)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtGui.QWidget(self.scrollArea_4)
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 444, 230))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.Headinglabel = QtGui.QLabel(self.scrollAreaWidgetContents_4)
        self.Headinglabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Headinglabel.setObjectName("Headinglabel")
        self.horizontalLayout_11.addWidget(self.Headinglabel)
        self.HandlingSpinBox = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_4)
        self.HandlingSpinBox.setMinimum(-360.0)
        self.HandlingSpinBox.setMaximum(360.0)
        self.HandlingSpinBox.setObjectName("HandlingSpinBox")
        self.horizontalLayout_11.addWidget(self.HandlingSpinBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.Pitchlabel = QtGui.QLabel(self.scrollAreaWidgetContents_4)
        self.Pitchlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Pitchlabel.setObjectName("Pitchlabel")
        self.horizontalLayout_11.addWidget(self.Pitchlabel)
        self.PitchSpinBox = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_4)
        self.PitchSpinBox.setMinimum(-90.0)
        self.PitchSpinBox.setMaximum(90.0)
        self.PitchSpinBox.setObjectName("PitchSpinBox")
        self.horizontalLayout_11.addWidget(self.PitchSpinBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.Rolllabel = QtGui.QLabel(self.scrollAreaWidgetContents_4)
        self.Rolllabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Rolllabel.setObjectName("Rolllabel")
        self.horizontalLayout_11.addWidget(self.Rolllabel)
        self.RollSpinBox = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_4)
        self.RollSpinBox.setAccelerated(False)
        self.RollSpinBox.setMinimum(-90.0)
        self.RollSpinBox.setMaximum(90.0)
        self.RollSpinBox.setObjectName("RollSpinBox")
        self.horizontalLayout_11.addWidget(self.RollSpinBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.line_2 = QtGui.QFrame(self.scrollAreaWidgetContents_4)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Zoomlabel = QtGui.QLabel(self.scrollAreaWidgetContents_4)
        self.Zoomlabel.setObjectName("Zoomlabel")
        self.horizontalLayout_4.addWidget(self.Zoomlabel)
        self.ZoomSpinBox = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZoomSpinBox.sizePolicy().hasHeightForWidth())
        self.ZoomSpinBox.setSizePolicy(sizePolicy)
        self.ZoomSpinBox.setAutoFillBackground(True)
        self.ZoomSpinBox.setWrapping(False)
        self.ZoomSpinBox.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.ZoomSpinBox.setAccelerated(True)
        self.ZoomSpinBox.setMinimum(-100.0)
        self.ZoomSpinBox.setMaximum(27536977.99)
        self.ZoomSpinBox.setObjectName("ZoomSpinBox")
        self.horizontalLayout_4.addWidget(self.ZoomSpinBox)
        self.ZoomStepSpinBox = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_4)
        self.ZoomStepSpinBox.setMinimum(0.0)
        self.ZoomStepSpinBox.setMaximum(100000.0)
        self.ZoomStepSpinBox.setSingleStep(1.0)
        self.ZoomStepSpinBox.setProperty("value", 100.0)
        self.ZoomStepSpinBox.setObjectName("ZoomStepSpinBox")
        self.horizontalLayout_4.addWidget(self.ZoomStepSpinBox)
        self.ZoomMultipler = QtGui.QSpinBox(self.scrollAreaWidgetContents_4)
        self.ZoomMultipler.setMinimum(0)
        self.ZoomMultipler.setObjectName("ZoomMultipler")
        self.horizontalLayout_4.addWidget(self.ZoomMultipler)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.line_3 = QtGui.QFrame(self.scrollAreaWidgetContents_4)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_5.addWidget(self.line_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Rangelabel = QtGui.QLabel(self.scrollAreaWidgetContents_4)
        self.Rangelabel.setObjectName("Rangelabel")
        self.horizontalLayout_6.addWidget(self.Rangelabel)
        self.RangeSpinBox = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RangeSpinBox.sizePolicy().hasHeightForWidth())
        self.RangeSpinBox.setSizePolicy(sizePolicy)
        self.RangeSpinBox.setAutoFillBackground(True)
        self.RangeSpinBox.setWrapping(True)
        self.RangeSpinBox.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.RangeSpinBox.setAccelerated(True)
        self.RangeSpinBox.setMinimum(-100.0)
        self.RangeSpinBox.setMaximum(27536977.99)
        self.RangeSpinBox.setObjectName("RangeSpinBox")
        self.horizontalLayout_6.addWidget(self.RangeSpinBox)
        self.RangeStepSpinBox = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_4)
        self.RangeStepSpinBox.setMinimum(0.0)
        self.RangeStepSpinBox.setMaximum(100000.0)
        self.RangeStepSpinBox.setSingleStep(1.0)
        self.RangeStepSpinBox.setProperty("value", 100.0)
        self.RangeStepSpinBox.setObjectName("RangeStepSpinBox")
        self.horizontalLayout_6.addWidget(self.RangeStepSpinBox)
        self.RangeMultipler = QtGui.QSpinBox(self.scrollAreaWidgetContents_4)
        self.RangeMultipler.setObjectName("RangeMultipler")
        self.horizontalLayout_6.addWidget(self.RangeMultipler)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.line_4 = QtGui.QFrame(self.scrollAreaWidgetContents_4)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_5.addWidget(self.line_4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents_4)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.SpeedSpinBox = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpeedSpinBox.sizePolicy().hasHeightForWidth())
        self.SpeedSpinBox.setSizePolicy(sizePolicy)
        self.SpeedSpinBox.setProperty("value", 1.0)
        self.SpeedSpinBox.setObjectName("SpeedSpinBox")
        self.horizontalLayout_7.addWidget(self.SpeedSpinBox)
        self.SpeedMultipler = QtGui.QSpinBox(self.scrollAreaWidgetContents_4)
        self.SpeedMultipler.setObjectName("SpeedMultipler")
        self.horizontalLayout_7.addWidget(self.SpeedMultipler)
        self.line = QtGui.QFrame(self.scrollAreaWidgetContents_4)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_7.addWidget(self.line)
        self.QgsSync = QtGui.QCheckBox(self.scrollAreaWidgetContents_4)
        self.QgsSync.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.QgsSync.setAutoFillBackground(False)
        self.QgsSync.setObjectName("QgsSync")
        self.horizontalLayout_7.addWidget(self.QgsSync)
        self.Head = QtGui.QComboBox(self.scrollAreaWidgetContents_4)
        self.Head.setModelColumn(0)
        self.Head.setObjectName("Head")
        self.Head.addItem("")
        self.Head.setItemText(0, "")
        self.Head.addItem("")
        self.Head.addItem("")
        self.Head.addItem("")
        self.Head.addItem("")
        self.Head.addItem("")
        self.Head.addItem("")
        self.Head.addItem("")
        self.Head.addItem("")
        self.Head.addItem("")
        self.Head.addItem("")
        self.horizontalLayout_7.addWidget(self.Head)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout.addWidget(self.scrollArea_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout = QtGui.QGridLayout(self.tab_3)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea_2 = QtGui.QScrollArea(self.tab_3)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget(self.scrollArea_2)
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 429, 271))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ZoomSlider = QtGui.QSlider(self.scrollAreaWidgetContents_2)
        self.ZoomSlider.setMinimum(-100)
        self.ZoomSlider.setMaximum(27536977)
        self.ZoomSlider.setProperty("value", 5000)
        self.ZoomSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ZoomSlider.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.ZoomSlider.setTickInterval(1000000)
        self.ZoomSlider.setObjectName("ZoomSlider")
        self.gridLayout_4.addWidget(self.ZoomSlider, 0, 0, 1, 1)
        self.Zoomlabel_2 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.Zoomlabel_2.setObjectName("Zoomlabel_2")
        self.gridLayout_4.addWidget(self.Zoomlabel_2, 0, 1, 1, 1)
        self.RangeSlider = QtGui.QSlider(self.scrollAreaWidgetContents_2)
        self.RangeSlider.setMaximum(27536977)
        self.RangeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.RangeSlider.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.RangeSlider.setTickInterval(1000000)
        self.RangeSlider.setObjectName("RangeSlider")
        self.gridLayout_4.addWidget(self.RangeSlider, 2, 0, 1, 1)
        self.Rangelabel_2 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.Rangelabel_2.setObjectName("Rangelabel_2")
        self.gridLayout_4.addWidget(self.Rangelabel_2, 2, 1, 1, 1)
        self.RollSlider = QtGui.QSlider(self.scrollAreaWidgetContents_2)
        self.RollSlider.setMinimum(-90)
        self.RollSlider.setMaximum(90)
        self.RollSlider.setOrientation(QtCore.Qt.Horizontal)
        self.RollSlider.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.RollSlider.setTickInterval(10)
        self.RollSlider.setObjectName("RollSlider")
        self.gridLayout_4.addWidget(self.RollSlider, 4, 0, 1, 1)
        self.Rolllabel_2 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.Rolllabel_2.setObjectName("Rolllabel_2")
        self.gridLayout_4.addWidget(self.Rolllabel_2, 4, 1, 1, 1)
        self.PitchSlider = QtGui.QSlider(self.scrollAreaWidgetContents_2)
        self.PitchSlider.setMinimum(-90)
        self.PitchSlider.setMaximum(90)
        self.PitchSlider.setOrientation(QtCore.Qt.Horizontal)
        self.PitchSlider.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.PitchSlider.setObjectName("PitchSlider")
        self.gridLayout_4.addWidget(self.PitchSlider, 6, 0, 1, 1)
        self.Pitchlabel_2 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.Pitchlabel_2.setObjectName("Pitchlabel_2")
        self.gridLayout_4.addWidget(self.Pitchlabel_2, 6, 1, 1, 1)
        self.HandlingSlider = QtGui.QSlider(self.scrollAreaWidgetContents_2)
        self.HandlingSlider.setMinimum(-360)
        self.HandlingSlider.setMaximum(360)
        self.HandlingSlider.setOrientation(QtCore.Qt.Horizontal)
        self.HandlingSlider.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.HandlingSlider.setTickInterval(10)
        self.HandlingSlider.setObjectName("HandlingSlider")
        self.gridLayout_4.addWidget(self.HandlingSlider, 8, 0, 1, 1)
        self.Headinglabel_2 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.Headinglabel_2.setObjectName("Headinglabel_2")
        self.gridLayout_4.addWidget(self.Headinglabel_2, 8, 1, 1, 1)
        self.line_8 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_4.addWidget(self.line_8, 1, 0, 1, 1)
        self.line_9 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_4.addWidget(self.line_9, 3, 0, 1, 1)
        self.line_10 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_4.addWidget(self.line_10, 5, 0, 1, 1)
        self.line_11 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_4.addWidget(self.line_11, 7, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 9, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.GpsGroupBox_2 = QtGui.QGroupBox(self.tab_4)
        self.GpsGroupBox_2.setObjectName("GpsGroupBox_2")
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.GpsGroupBox_2)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.scrollArea = QtGui.QScrollArea(self.GpsGroupBox_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 399, 251))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.GpsGridLayout = QtGui.QGridLayout()
        self.GpsGridLayout.setObjectName("GpsGridLayout")
        self.Latlabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.Latlabel.setObjectName("Latlabel")
        self.GpsGridLayout.addWidget(self.Latlabel, 0, 0, 1, 1)
        self.GPSlat = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.GPSlat.setEchoMode(QtGui.QLineEdit.Normal)
        self.GPSlat.setAlignment(QtCore.Qt.AlignCenter)
        self.GPSlat.setReadOnly(True)
        self.GPSlat.setObjectName("GPSlat")
        self.GpsGridLayout.addWidget(self.GPSlat, 0, 2, 1, 1)
        self.GPSEpt = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.GPSEpt.setAlignment(QtCore.Qt.AlignCenter)
        self.GPSEpt.setReadOnly(True)
        self.GPSEpt.setObjectName("GPSEpt")
        self.GpsGridLayout.addWidget(self.GPSEpt, 7, 2, 1, 1)
        self.Eptlabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.Eptlabel.setObjectName("Eptlabel")
        self.GpsGridLayout.addWidget(self.Eptlabel, 7, 0, 1, 1)
        self.GPSAltitude = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.GPSAltitude.setAlignment(QtCore.Qt.AlignCenter)
        self.GPSAltitude.setReadOnly(True)
        self.GPSAltitude.setObjectName("GPSAltitude")
        self.GpsGridLayout.addWidget(self.GPSAltitude, 4, 2, 1, 1)
        self.Altitudelabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.Altitudelabel.setObjectName("Altitudelabel")
        self.GpsGridLayout.addWidget(self.Altitudelabel, 4, 0, 1, 1)
        self.GPSEps = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.GPSEps.setAlignment(QtCore.Qt.AlignCenter)
        self.GPSEps.setReadOnly(True)
        self.GPSEps.setObjectName("GPSEps")
        self.GpsGridLayout.addWidget(self.GPSEps, 9, 2, 1, 1)
        self.Epslabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.Epslabel.setObjectName("Epslabel")
        self.GpsGridLayout.addWidget(self.Epslabel, 9, 0, 1, 1)
        self.Lonlabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.Lonlabel.setObjectName("Lonlabel")
        self.GpsGridLayout.addWidget(self.Lonlabel, 0, 3, 1, 1)
        self.GPSlon = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.GPSlon.setAlignment(QtCore.Qt.AlignCenter)
        self.GPSlon.setReadOnly(True)
        self.GPSlon.setObjectName("GPSlon")
        self.GpsGridLayout.addWidget(self.GPSlon, 0, 4, 1, 1)
        self.Speedlabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.Speedlabel.setObjectName("Speedlabel")
        self.GpsGridLayout.addWidget(self.Speedlabel, 4, 3, 1, 1)
        self.GPSSpeed = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.GPSSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.GPSSpeed.setReadOnly(True)
        self.GPSSpeed.setObjectName("GPSSpeed")
        self.GpsGridLayout.addWidget(self.GPSSpeed, 4, 4, 1, 1)
        self.GPSClimb = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.GPSClimb.setAlignment(QtCore.Qt.AlignCenter)
        self.GPSClimb.setReadOnly(True)
        self.GPSClimb.setObjectName("GPSClimb")
        self.GpsGridLayout.addWidget(self.GPSClimb, 5, 4, 1, 1)
        self.Climblabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.Climblabel.setObjectName("Climblabel")
        self.GpsGridLayout.addWidget(self.Climblabel, 5, 3, 1, 1)
        self.GPSEpc = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.GPSEpc.setAlignment(QtCore.Qt.AlignCenter)
        self.GPSEpc.setReadOnly(True)
        self.GPSEpc.setObjectName("GPSEpc")
        self.GpsGridLayout.addWidget(self.GPSEpc, 9, 4, 1, 1)
        self.Epclabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.Epclabel.setObjectName("Epclabel")
        self.GpsGridLayout.addWidget(self.Epclabel, 9, 3, 1, 1)
        self.GPSEpv = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.GPSEpv.setAlignment(QtCore.Qt.AlignCenter)
        self.GPSEpv.setReadOnly(True)
        self.GPSEpv.setObjectName("GPSEpv")
        self.GpsGridLayout.addWidget(self.GPSEpv, 6, 4, 1, 1)
        self.Epvlabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.Epvlabel.setObjectName("Epvlabel")
        self.GpsGridLayout.addWidget(self.Epvlabel, 6, 3, 1, 1)
        self.Ephlabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.Ephlabel.setObjectName("Ephlabel")
        self.GpsGridLayout.addWidget(self.Ephlabel, 6, 0, 1, 1)
        self.GPSEph = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.GPSEph.setAlignment(QtCore.Qt.AlignCenter)
        self.GPSEph.setReadOnly(True)
        self.GPSEph.setObjectName("GPSEph")
        self.GpsGridLayout.addWidget(self.GPSEph, 6, 2, 1, 1)
        self.Tracklabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.Tracklabel.setObjectName("Tracklabel")
        self.GpsGridLayout.addWidget(self.Tracklabel, 5, 0, 1, 1)
        self.GPSTrack = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.GPSTrack.setAlignment(QtCore.Qt.AlignCenter)
        self.GPSTrack.setReadOnly(True)
        self.GPSTrack.setObjectName("GPSTrack")
        self.GpsGridLayout.addWidget(self.GPSTrack, 5, 2, 1, 1)
        self.Epdlabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.Epdlabel.setObjectName("Epdlabel")
        self.GpsGridLayout.addWidget(self.Epdlabel, 7, 3, 1, 1)
        self.GPSEpd = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.GPSEpd.setAlignment(QtCore.Qt.AlignCenter)
        self.GPSEpd.setReadOnly(True)
        self.GPSEpd.setObjectName("GPSEpd")
        self.GpsGridLayout.addWidget(self.GPSEpd, 7, 4, 1, 1)
        self.Datelabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.Datelabel.setObjectName("Datelabel")
        self.GpsGridLayout.addWidget(self.Datelabel, 2, 0, 1, 1)
        self.Utclabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.Utclabel.setObjectName("Utclabel")
        self.GpsGridLayout.addWidget(self.Utclabel, 2, 3, 1, 1)
        self.GPSUtctime = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.GPSUtctime.setAlignment(QtCore.Qt.AlignCenter)
        self.GPSUtctime.setReadOnly(True)
        self.GPSUtctime.setObjectName("GPSUtctime")
        self.GpsGridLayout.addWidget(self.GPSUtctime, 2, 4, 1, 1)
        self.GPSTime = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.GPSTime.setAlignment(QtCore.Qt.AlignCenter)
        self.GPSTime.setReadOnly(True)
        self.GPSTime.setObjectName("GPSTime")
        self.GpsGridLayout.addWidget(self.GPSTime, 2, 2, 1, 1)
        self.GPSPdop = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.GPSPdop.setAlignment(QtCore.Qt.AlignCenter)
        self.GPSPdop.setReadOnly(True)
        self.GPSPdop.setObjectName("GPSPdop")
        self.GpsGridLayout.addWidget(self.GPSPdop, 0, 6, 1, 1)
        self.Pdoplabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.Pdoplabel.setObjectName("Pdoplabel")
        self.GpsGridLayout.addWidget(self.Pdoplabel, 0, 5, 1, 1)
        self.GPSHdop = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.GPSHdop.setAlignment(QtCore.Qt.AlignCenter)
        self.GPSHdop.setReadOnly(True)
        self.GPSHdop.setObjectName("GPSHdop")
        self.GpsGridLayout.addWidget(self.GPSHdop, 2, 6, 1, 1)
        self.GPSVdop = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.GPSVdop.setAlignment(QtCore.Qt.AlignCenter)
        self.GPSVdop.setReadOnly(True)
        self.GPSVdop.setObjectName("GPSVdop")
        self.GpsGridLayout.addWidget(self.GPSVdop, 4, 6, 1, 1)
        self.GPSTdop = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.GPSTdop.setAlignment(QtCore.Qt.AlignCenter)
        self.GPSTdop.setReadOnly(True)
        self.GPSTdop.setObjectName("GPSTdop")
        self.GpsGridLayout.addWidget(self.GPSTdop, 5, 6, 1, 1)
        self.GPSGdop = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.GPSGdop.setAlignment(QtCore.Qt.AlignCenter)
        self.GPSGdop.setReadOnly(True)
        self.GPSGdop.setObjectName("GPSGdop")
        self.GpsGridLayout.addWidget(self.GPSGdop, 6, 6, 1, 1)
        self.Hdoplabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.Hdoplabel.setObjectName("Hdoplabel")
        self.GpsGridLayout.addWidget(self.Hdoplabel, 2, 5, 1, 1)
        self.Vdoplabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.Vdoplabel.setObjectName("Vdoplabel")
        self.GpsGridLayout.addWidget(self.Vdoplabel, 4, 5, 1, 1)
        self.Tdoplabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.Tdoplabel.setObjectName("Tdoplabel")
        self.GpsGridLayout.addWidget(self.Tdoplabel, 5, 5, 1, 1)
        self.Gdoplabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.Gdoplabel.setObjectName("Gdoplabel")
        self.GpsGridLayout.addWidget(self.Gdoplabel, 6, 5, 1, 1)
        self.StartGps = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.StartGps.setCheckable(True)
        self.StartGps.setObjectName("StartGps")
        self.GpsGridLayout.addWidget(self.StartGps, 9, 6, 1, 1)
        self.GPSSend = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.GPSSend.setObjectName("GPSSend")
        self.GpsGridLayout.addWidget(self.GPSSend, 7, 6, 1, 1)
        self.gridLayout_3.addLayout(self.GpsGridLayout, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_20.addWidget(self.scrollArea)
        self.gridLayout_2.addWidget(self.GpsGroupBox_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        OssimPlanetSasha.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(OssimPlanetSasha)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 642, 22))
        self.menubar.setObjectName("menubar")
        self.menuSasha = QtGui.QMenu(self.menubar)
        self.menuSasha.setObjectName("menuSasha")
        OssimPlanetSasha.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(OssimPlanetSasha)
        self.statusbar.setObjectName("statusbar")
        OssimPlanetSasha.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(OssimPlanetSasha)
        self.toolBar.setObjectName("toolBar")
        OssimPlanetSasha.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLonLat = QtGui.QAction(OssimPlanetSasha)
        self.actionLonLat.setCheckable(True)
        self.actionLonLat.setChecked(False)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/mActionMoveItemContent.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLonLat.setIcon(icon14)
        self.actionLonLat.setObjectName("actionLonLat")
        self.actionExit = QtGui.QAction(OssimPlanetSasha)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/icons/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon15)
        self.actionExit.setObjectName("actionExit")
        self.actionSavekml = QtGui.QAction(OssimPlanetSasha)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/mActionNewBookmark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSavekml.setIcon(icon16)
        self.actionSavekml.setObjectName("actionSavekml")
        self.actionEpsg = QtGui.QAction(OssimPlanetSasha)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/600px-Brosen_windrose.svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEpsg.setIcon(icon17)
        self.actionEpsg.setObjectName("actionEpsg")
        self.actionDataexp = QtGui.QAction(OssimPlanetSasha)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons/mActionNewVectorLayer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDataexp.setIcon(icon18)
        self.actionDataexp.setObjectName("actionDataexp")
        self.actionModel = QtGui.QAction(OssimPlanetSasha)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icons/cubo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionModel.setIcon(icon19)
        self.actionModel.setObjectName("actionModel")
        self.actionPref = QtGui.QAction(OssimPlanetSasha)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/icons/mActionOptions.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPref.setIcon(icon20)
        self.actionPref.setObjectName("actionPref")
        self.actionVectorOp = QtGui.QAction(OssimPlanetSasha)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/icons/SquadraCompasso.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVectorOp.setIcon(icon21)
        self.actionVectorOp.setObjectName("actionVectorOp")
        self.actionQaddfiles = QtGui.QAction(OssimPlanetSasha)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/icons/mActionDraw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQaddfiles.setIcon(icon22)
        self.actionQaddfiles.setObjectName("actionQaddfiles")
        self.actionRefresh = QtGui.QAction(OssimPlanetSasha)
        self.actionRefresh.setIcon(icon22)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionHide = QtGui.QAction(OssimPlanetSasha)
        self.actionHide.setCheckable(True)
        self.actionHide.setObjectName("actionHide")
        self.actionPicker = QtGui.QAction(OssimPlanetSasha)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/icons/mActionPan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPicker.setIcon(icon23)
        self.actionPicker.setObjectName("actionPicker")
        self.menuSasha.addAction(self.actionPref)
        self.menuSasha.addAction(self.actionHide)
        self.menubar.addAction(self.menuSasha.menuAction())
        self.toolBar.addAction(self.actionLonLat)
        self.toolBar.addAction(self.actionPicker)
        self.toolBar.addAction(self.actionQaddfiles)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSavekml)
        self.toolBar.addAction(self.actionDataexp)
        self.toolBar.addAction(self.actionModel)
        self.toolBar.addAction(self.actionVectorOp)
        self.toolBar.addAction(self.actionEpsg)
        self.toolBar.addAction(self.actionPref)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(OssimPlanetSasha)
        self.tabWidget.setCurrentIndex(0)
        self.Head.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(OssimPlanetSasha)

    def retranslateUi(self, OssimPlanetSasha):
        OssimPlanetSasha.setWindowTitle(QtGui.QApplication.translate("OssimPlanetSasha", "PlanetSasha", None, QtGui.QApplication.UnicodeUTF8))
        self.northwest.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "NordWest", None, QtGui.QApplication.UnicodeUTF8))
        self.north.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "North", None, QtGui.QApplication.UnicodeUTF8))
        self.northeast.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "NordEast", None, QtGui.QApplication.UnicodeUTF8))
        self.west.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "West", None, QtGui.QApplication.UnicodeUTF8))
        self.west.setText(QtGui.QApplication.translate("OssimPlanetSasha", " W", None, QtGui.QApplication.UnicodeUTF8))
        self.east.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "East", None, QtGui.QApplication.UnicodeUTF8))
        self.east.setText(QtGui.QApplication.translate("OssimPlanetSasha", " E ", None, QtGui.QApplication.UnicodeUTF8))
        self.southwest.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "SouthWest", None, QtGui.QApplication.UnicodeUTF8))
        self.south.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "South", None, QtGui.QApplication.UnicodeUTF8))
        self.south.setText(QtGui.QApplication.translate("OssimPlanetSasha", " S ", None, QtGui.QApplication.UnicodeUTF8))
        self.southeast.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "SouthEast", None, QtGui.QApplication.UnicodeUTF8))
        self.Lat.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "Longitude", None, QtGui.QApplication.UnicodeUTF8))
        self.Lon.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "Latitude", None, QtGui.QApplication.UnicodeUTF8))
        self.SendPosition.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "Go to lat lon", None, QtGui.QApplication.UnicodeUTF8))
        self.SendPosition.setText(QtGui.QApplication.translate("OssimPlanetSasha", "GO", None, QtGui.QApplication.UnicodeUTF8))
        self.Nord.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "UTM coordinates - North", None, QtGui.QApplication.UnicodeUTF8))
        self.East.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "UTM coordinates - East", None, QtGui.QApplication.UnicodeUTF8))
        self.utmcode.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "UTM zone", None, QtGui.QApplication.UnicodeUTF8))
        self.ellipse.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "Ellipsoid", None, QtGui.QApplication.UnicodeUTF8))
        self.ellipse.setItemText(0, QtGui.QApplication.translate("OssimPlanetSasha", "WGS-84", None, QtGui.QApplication.UnicodeUTF8))
        self.ellipse.setItemText(1, QtGui.QApplication.translate("OssimPlanetSasha", "Airy", None, QtGui.QApplication.UnicodeUTF8))
        self.ellipse.setItemText(2, QtGui.QApplication.translate("OssimPlanetSasha", "Australian National", None, QtGui.QApplication.UnicodeUTF8))
        self.ellipse.setItemText(3, QtGui.QApplication.translate("OssimPlanetSasha", "Bessel 1841", None, QtGui.QApplication.UnicodeUTF8))
        self.ellipse.setItemText(4, QtGui.QApplication.translate("OssimPlanetSasha", "Bessel 1841 (Nambia)", None, QtGui.QApplication.UnicodeUTF8))
        self.ellipse.setItemText(5, QtGui.QApplication.translate("OssimPlanetSasha", "Clarke 1866", None, QtGui.QApplication.UnicodeUTF8))
        self.ellipse.setItemText(6, QtGui.QApplication.translate("OssimPlanetSasha", "Clarke 1880", None, QtGui.QApplication.UnicodeUTF8))
        self.ellipse.setItemText(7, QtGui.QApplication.translate("OssimPlanetSasha", "Everest", None, QtGui.QApplication.UnicodeUTF8))
        self.ellipse.setItemText(8, QtGui.QApplication.translate("OssimPlanetSasha", "Fischer 1960 (Mercury)", None, QtGui.QApplication.UnicodeUTF8))
        self.ellipse.setItemText(9, QtGui.QApplication.translate("OssimPlanetSasha", "Fischer 1968", None, QtGui.QApplication.UnicodeUTF8))
        self.ellipse.setItemText(10, QtGui.QApplication.translate("OssimPlanetSasha", "GRS 1967", None, QtGui.QApplication.UnicodeUTF8))
        self.ellipse.setItemText(11, QtGui.QApplication.translate("OssimPlanetSasha", "GRS 1980", None, QtGui.QApplication.UnicodeUTF8))
        self.ellipse.setItemText(12, QtGui.QApplication.translate("OssimPlanetSasha", "Helmert 1906", None, QtGui.QApplication.UnicodeUTF8))
        self.ellipse.setItemText(13, QtGui.QApplication.translate("OssimPlanetSasha", "Hough", None, QtGui.QApplication.UnicodeUTF8))
        self.ellipse.setItemText(14, QtGui.QApplication.translate("OssimPlanetSasha", "International", None, QtGui.QApplication.UnicodeUTF8))
        self.ellipse.setItemText(15, QtGui.QApplication.translate("OssimPlanetSasha", "Krassovsky", None, QtGui.QApplication.UnicodeUTF8))
        self.ellipse.setItemText(16, QtGui.QApplication.translate("OssimPlanetSasha", "Modified Airy", None, QtGui.QApplication.UnicodeUTF8))
        self.ellipse.setItemText(17, QtGui.QApplication.translate("OssimPlanetSasha", "Modified Everest", None, QtGui.QApplication.UnicodeUTF8))
        self.ellipse.setItemText(18, QtGui.QApplication.translate("OssimPlanetSasha", "Modified Fischer 1960", None, QtGui.QApplication.UnicodeUTF8))
        self.ellipse.setItemText(19, QtGui.QApplication.translate("OssimPlanetSasha", "South American 1969", None, QtGui.QApplication.UnicodeUTF8))
        self.ellipse.setItemText(20, QtGui.QApplication.translate("OssimPlanetSasha", "WGS 60", None, QtGui.QApplication.UnicodeUTF8))
        self.ellipse.setItemText(21, QtGui.QApplication.translate("OssimPlanetSasha", "WGS 66", None, QtGui.QApplication.UnicodeUTF8))
        self.ellipse.setItemText(22, QtGui.QApplication.translate("OssimPlanetSasha", "WGS-72", None, QtGui.QApplication.UnicodeUTF8))
        self.ellipse.setItemText(23, QtGui.QApplication.translate("OssimPlanetSasha", "WGS-84", None, QtGui.QApplication.UnicodeUTF8))
        self.addqlayer.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "Add Raster Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.addqlayer.setText(QtGui.QApplication.translate("OssimPlanetSasha", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.removeqlayer.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "Remove Raster Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.removeqlayer.setText(QtGui.QApplication.translate("OssimPlanetSasha", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.qgislayer.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "Raster Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.addVlayer.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "Add Vector Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.addVlayer.setText(QtGui.QApplication.translate("OssimPlanetSasha", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.removeVlayer.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "Remove Vector Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.removeVlayer.setText(QtGui.QApplication.translate("OssimPlanetSasha", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.qgisVlayer.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "Vector Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.Place.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "Geonames Zone", None, QtGui.QApplication.UnicodeUTF8))
        self.placezone.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "Geonames Place", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("OssimPlanetSasha", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.Headinglabel.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Heading ", None, QtGui.QApplication.UnicodeUTF8))
        self.Pitchlabel.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Pitch", None, QtGui.QApplication.UnicodeUTF8))
        self.Rolllabel.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Roll ", None, QtGui.QApplication.UnicodeUTF8))
        self.Zoomlabel.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Zoom ", None, QtGui.QApplication.UnicodeUTF8))
        self.ZoomSpinBox.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "Zoom (altitude) value in meters", None, QtGui.QApplication.UnicodeUTF8))
        self.ZoomStepSpinBox.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "Zoom Step in meters", None, QtGui.QApplication.UnicodeUTF8))
        self.ZoomMultipler.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "ZStep - 10^x  multipler", None, QtGui.QApplication.UnicodeUTF8))
        self.Rangelabel.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Range ", None, QtGui.QApplication.UnicodeUTF8))
        self.RangeSpinBox.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "Range (distance) in meters", None, QtGui.QApplication.UnicodeUTF8))
        self.RangeStepSpinBox.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "Zoom Step in meters", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Pan", None, QtGui.QApplication.UnicodeUTF8))
        self.SpeedSpinBox.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "Pan Step in decimal degrees", None, QtGui.QApplication.UnicodeUTF8))
        self.SpeedMultipler.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "PStep - 10^-x  multipler", None, QtGui.QApplication.UnicodeUTF8))
        self.QgsSync.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Sync", None, QtGui.QApplication.UnicodeUTF8))
        self.Head.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "Heading mode", None, QtGui.QApplication.UnicodeUTF8))
        self.Head.setItemText(1, QtGui.QApplication.translate("OssimPlanetSasha", "Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.Head.setItemText(2, QtGui.QApplication.translate("OssimPlanetSasha", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.Head.setItemText(3, QtGui.QApplication.translate("OssimPlanetSasha", "N", None, QtGui.QApplication.UnicodeUTF8))
        self.Head.setItemText(4, QtGui.QApplication.translate("OssimPlanetSasha", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.Head.setItemText(5, QtGui.QApplication.translate("OssimPlanetSasha", "SE", None, QtGui.QApplication.UnicodeUTF8))
        self.Head.setItemText(6, QtGui.QApplication.translate("OssimPlanetSasha", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.Head.setItemText(7, QtGui.QApplication.translate("OssimPlanetSasha", "SW", None, QtGui.QApplication.UnicodeUTF8))
        self.Head.setItemText(8, QtGui.QApplication.translate("OssimPlanetSasha", "W", None, QtGui.QApplication.UnicodeUTF8))
        self.Head.setItemText(9, QtGui.QApplication.translate("OssimPlanetSasha", "NW", None, QtGui.QApplication.UnicodeUTF8))
        self.Head.setItemText(10, QtGui.QApplication.translate("OssimPlanetSasha", "NE", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("OssimPlanetSasha", "PView", None, QtGui.QApplication.UnicodeUTF8))
        self.Zoomlabel_2.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Zoom ", None, QtGui.QApplication.UnicodeUTF8))
        self.Rangelabel_2.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Range ", None, QtGui.QApplication.UnicodeUTF8))
        self.Rolllabel_2.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Roll ", None, QtGui.QApplication.UnicodeUTF8))
        self.Pitchlabel_2.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Pitch", None, QtGui.QApplication.UnicodeUTF8))
        self.Headinglabel_2.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Heading ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("OssimPlanetSasha", "SView", None, QtGui.QApplication.UnicodeUTF8))
        self.Latlabel.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Lat", None, QtGui.QApplication.UnicodeUTF8))
        self.Eptlabel.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Ept", None, QtGui.QApplication.UnicodeUTF8))
        self.Altitudelabel.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Altitude", None, QtGui.QApplication.UnicodeUTF8))
        self.Epslabel.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Eps", None, QtGui.QApplication.UnicodeUTF8))
        self.Lonlabel.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Lon", None, QtGui.QApplication.UnicodeUTF8))
        self.Speedlabel.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.Climblabel.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Climb", None, QtGui.QApplication.UnicodeUTF8))
        self.Epclabel.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Epc", None, QtGui.QApplication.UnicodeUTF8))
        self.Epvlabel.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Epv", None, QtGui.QApplication.UnicodeUTF8))
        self.Ephlabel.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Eph", None, QtGui.QApplication.UnicodeUTF8))
        self.Tracklabel.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Track", None, QtGui.QApplication.UnicodeUTF8))
        self.Epdlabel.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Epd", None, QtGui.QApplication.UnicodeUTF8))
        self.Datelabel.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.Utclabel.setText(QtGui.QApplication.translate("OssimPlanetSasha", "UTC", None, QtGui.QApplication.UnicodeUTF8))
        self.Pdoplabel.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Pdop", None, QtGui.QApplication.UnicodeUTF8))
        self.Hdoplabel.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Hdop", None, QtGui.QApplication.UnicodeUTF8))
        self.Vdoplabel.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Vdop", None, QtGui.QApplication.UnicodeUTF8))
        self.Tdoplabel.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Tdop", None, QtGui.QApplication.UnicodeUTF8))
        self.Gdoplabel.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Gdop", None, QtGui.QApplication.UnicodeUTF8))
        self.StartGps.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Start/Stop ", None, QtGui.QApplication.UnicodeUTF8))
        self.GPSSend.setText(QtGui.QApplication.translate("OssimPlanetSasha", "SendPosition", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("OssimPlanetSasha", "GPS", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSasha.setTitle(QtGui.QApplication.translate("OssimPlanetSasha", "Sasha", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("OssimPlanetSasha", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLonLat.setText(QtGui.QApplication.translate("OssimPlanetSasha", "LonLat", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLonLat.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "Pan mode", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Preference", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "Quit Qgis", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSavekml.setText(QtGui.QApplication.translate("OssimPlanetSasha", "savekml", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSavekml.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "save waypoint as kml", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEpsg.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Epsg", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEpsg.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "Select Epsg reference code", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDataexp.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Create kml / Elevation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionModel.setText(QtGui.QApplication.translate("OssimPlanetSasha", "model", None, QtGui.QApplication.UnicodeUTF8))
        self.actionModel.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "3D model positioning tool", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPref.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Pref", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPref.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "Preference", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVectorOp.setText(QtGui.QApplication.translate("OssimPlanetSasha", "VectorOp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVectorOp.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "Traslate / Rotate / Scale / REproject - vector file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQaddfiles.setText(QtGui.QApplication.translate("OssimPlanetSasha", "Qaddraster", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQaddfiles.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "Refresh qgis layers", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh.setText(QtGui.QApplication.translate("OssimPlanetSasha", "refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHide.setText(QtGui.QApplication.translate("OssimPlanetSasha", "hide tab widjet", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPicker.setText(QtGui.QApplication.translate("OssimPlanetSasha", "picker", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPicker.setToolTip(QtGui.QApplication.translate("OssimPlanetSasha", "activate the picker function", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
