###
# $Id: Makefile 10395 2007-01-29 19:43:49Z dburken $
###

all:
	cd oms; $(MAKE) all

clean:
	cd oms; $(MAKE) clean

depends:
	cd oms; $(MAKE) depends

install:
	cd oms; $(MAKE) install

uninstall:
	cd oms; $(MAKE) uninstall

