# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/sasha/.qgis/python/plugins/Qplanet/ui/model_ui.ui'
#
# Created: Tue Nov 24 21:55:03 2009
#      by: PyQt4 UI code generator 4.6.2-snapshot-20091115
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(363, 251)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/cubo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout_9 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.scrollArea = QtGui.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 320, 747))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.KmlGeneralgroupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.KmlGeneralgroupBox.setObjectName("KmlGeneralgroupBox")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.KmlGeneralgroupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.KmlGeneralgroupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.kmlname = QtGui.QLineEdit(self.KmlGeneralgroupBox)
        self.kmlname.setObjectName("kmlname")
        self.gridLayout.addWidget(self.kmlname, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.KmlGeneralgroupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.kmllabel = QtGui.QLineEdit(self.KmlGeneralgroupBox)
        self.kmllabel.setObjectName("kmllabel")
        self.gridLayout.addWidget(self.kmllabel, 1, 2, 1, 1)
        self.Iconlabel = QtGui.QLabel(self.KmlGeneralgroupBox)
        self.Iconlabel.setObjectName("Iconlabel")
        self.gridLayout.addWidget(self.Iconlabel, 2, 0, 1, 1)
        self.LineWidthlabel = QtGui.QLabel(self.KmlGeneralgroupBox)
        self.LineWidthlabel.setObjectName("LineWidthlabel")
        self.gridLayout.addWidget(self.LineWidthlabel, 3, 0, 1, 1)
        self.altitudemode = QtGui.QComboBox(self.KmlGeneralgroupBox)
        self.altitudemode.setObjectName("altitudemode")
        self.altitudemode.addItem("")
        self.altitudemode.addItem("")
        self.altitudemode.addItem("")
        self.gridLayout.addWidget(self.altitudemode, 3, 2, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectmodel = QtGui.QToolButton(self.KmlGeneralgroupBox)
        self.selectmodel.setIcon(icon)
        self.selectmodel.setObjectName("selectmodel")
        self.horizontalLayout.addWidget(self.selectmodel)
        self.modelpath = QtGui.QLineEdit(self.KmlGeneralgroupBox)
        self.modelpath.setObjectName("modelpath")
        self.horizontalLayout.addWidget(self.modelpath)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 2, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.KmlGeneralgroupBox)
        self.KmlColorgroupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.KmlColorgroupBox.setObjectName("KmlColorgroupBox")
        self.gridLayout_29 = QtGui.QGridLayout(self.KmlColorgroupBox)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.tabWidget = QtGui.QTabWidget(self.KmlColorgroupBox)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.CameraHeading = QtGui.QLineEdit(self.tab)
        self.CameraHeading.setObjectName("CameraHeading")
        self.gridLayout_3.addWidget(self.CameraHeading, 1, 1, 1, 1)
        self.CameraTilt = QtGui.QLineEdit(self.tab)
        self.CameraTilt.setObjectName("CameraTilt")
        self.gridLayout_3.addWidget(self.CameraTilt, 2, 1, 1, 1)
        self.CameraLatitude = QtGui.QLineEdit(self.tab)
        self.CameraLatitude.setObjectName("CameraLatitude")
        self.gridLayout_3.addWidget(self.CameraLatitude, 3, 1, 1, 1)
        self.CameraLongitude = QtGui.QLineEdit(self.tab)
        self.CameraLongitude.setObjectName("CameraLongitude")
        self.gridLayout_3.addWidget(self.CameraLongitude, 4, 1, 1, 1)
        self.CameraRange = QtGui.QLineEdit(self.tab)
        self.CameraRange.setObjectName("CameraRange")
        self.gridLayout_3.addWidget(self.CameraRange, 5, 1, 1, 1)
        self.CameraAltitude = QtGui.QLineEdit(self.tab)
        self.CameraAltitude.setObjectName("CameraAltitude")
        self.gridLayout_3.addWidget(self.CameraAltitude, 6, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 6, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.setcamera = QtGui.QPushButton(self.tab)
        self.setcamera.setObjectName("setcamera")
        self.verticalLayout_3.addWidget(self.setcamera)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 2, 0, 1, 1)
        self.ModelTilt = QtGui.QLineEdit(self.tab_2)
        self.ModelTilt.setObjectName("ModelTilt")
        self.gridLayout_4.addWidget(self.ModelTilt, 2, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 3, 0, 1, 1)
        self.ModelLatitude = QtGui.QLineEdit(self.tab_2)
        self.ModelLatitude.setObjectName("ModelLatitude")
        self.gridLayout_4.addWidget(self.ModelLatitude, 3, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 4, 0, 1, 1)
        self.ModelLongitude = QtGui.QLineEdit(self.tab_2)
        self.ModelLongitude.setObjectName("ModelLongitude")
        self.gridLayout_4.addWidget(self.ModelLongitude, 4, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 5, 0, 1, 1)
        self.ModelRange = QtGui.QLineEdit(self.tab_2)
        self.ModelRange.setObjectName("ModelRange")
        self.gridLayout_4.addWidget(self.ModelRange, 5, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 6, 0, 1, 1)
        self.ModelAltitude = QtGui.QLineEdit(self.tab_2)
        self.ModelAltitude.setObjectName("ModelAltitude")
        self.gridLayout_4.addWidget(self.ModelAltitude, 6, 1, 1, 1)
        self.ModelHeading = QtGui.QLineEdit(self.tab_2)
        self.ModelHeading.setObjectName("ModelHeading")
        self.gridLayout_4.addWidget(self.ModelHeading, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        self.setmodel = QtGui.QPushButton(self.tab_2)
        self.setmodel.setObjectName("setmodel")
        self.verticalLayout_4.addWidget(self.setmodel)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_29.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.KmlColorgroupBox)
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget_2 = QtGui.QTabWidget(self.groupBox)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_15 = QtGui.QLabel(self.tab_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 0, 0, 1, 1)
        self.MLongitude = QtGui.QLineEdit(self.tab_3)
        self.MLongitude.setObjectName("MLongitude")
        self.gridLayout_5.addWidget(self.MLongitude, 0, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 1, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.tab_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 2, 0, 1, 1)
        self.MLatitude = QtGui.QLineEdit(self.tab_3)
        self.MLatitude.setObjectName("MLatitude")
        self.gridLayout_5.addWidget(self.MLatitude, 1, 1, 1, 1)
        self.MAltitude = QtGui.QLineEdit(self.tab_3)
        self.MAltitude.setObjectName("MAltitude")
        self.gridLayout_5.addWidget(self.MAltitude, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.setlonlat = QtGui.QPushButton(self.tab_3)
        self.setlonlat.setObjectName("setlonlat")
        self.verticalLayout.addWidget(self.setlonlat)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_28 = QtGui.QLabel(self.tab_4)
        self.label_28.setObjectName("label_28")
        self.gridLayout_6.addWidget(self.label_28, 0, 0, 1, 1)
        self.label_29 = QtGui.QLabel(self.tab_4)
        self.label_29.setObjectName("label_29")
        self.gridLayout_6.addWidget(self.label_29, 1, 0, 1, 1)
        self.label_30 = QtGui.QLabel(self.tab_4)
        self.label_30.setObjectName("label_30")
        self.gridLayout_6.addWidget(self.label_30, 2, 0, 1, 1)
        self.MHeading = QtGui.QLineEdit(self.tab_4)
        self.MHeading.setObjectName("MHeading")
        self.gridLayout_6.addWidget(self.MHeading, 0, 1, 1, 1)
        self.MTilt = QtGui.QLineEdit(self.tab_4)
        self.MTilt.setObjectName("MTilt")
        self.gridLayout_6.addWidget(self.MTilt, 1, 1, 1, 1)
        self.MRoll = QtGui.QLineEdit(self.tab_4)
        self.MRoll.setObjectName("MRoll")
        self.gridLayout_6.addWidget(self.MRoll, 2, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_6)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_36 = QtGui.QLabel(self.tab_5)
        self.label_36.setObjectName("label_36")
        self.gridLayout_7.addWidget(self.label_36, 0, 0, 1, 1)
        self.label_37 = QtGui.QLabel(self.tab_5)
        self.label_37.setObjectName("label_37")
        self.gridLayout_7.addWidget(self.label_37, 1, 0, 1, 1)
        self.label_38 = QtGui.QLabel(self.tab_5)
        self.label_38.setObjectName("label_38")
        self.gridLayout_7.addWidget(self.label_38, 2, 0, 1, 1)
        self.Xscale = QtGui.QLineEdit(self.tab_5)
        self.Xscale.setObjectName("Xscale")
        self.gridLayout_7.addWidget(self.Xscale, 0, 1, 1, 1)
        self.Yscale = QtGui.QLineEdit(self.tab_5)
        self.Yscale.setObjectName("Yscale")
        self.gridLayout_7.addWidget(self.Yscale, 1, 1, 1, 1)
        self.Zscale = QtGui.QLineEdit(self.tab_5)
        self.Zscale.setObjectName("Zscale")
        self.gridLayout_7.addWidget(self.Zscale, 2, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_7)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.verticalLayout_5.addWidget(self.tabWidget_2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_9.addWidget(self.scrollArea)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.save = QtGui.QPushButton(Form)
        self.save.setObjectName("save")
        self.horizontalLayout_8.addWidget(self.save)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.KmlGeneralgroupBox.setTitle(QtGui.QApplication.translate("Form", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Kml-Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Model-Name", None, QtGui.QApplication.UnicodeUTF8))
        self.Iconlabel.setText(QtGui.QApplication.translate("Form", "Mode-Path", None, QtGui.QApplication.UnicodeUTF8))
        self.LineWidthlabel.setText(QtGui.QApplication.translate("Form", "Altitude-Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.altitudemode.setItemText(0, QtGui.QApplication.translate("Form", "absolute", None, QtGui.QApplication.UnicodeUTF8))
        self.altitudemode.setItemText(1, QtGui.QApplication.translate("Form", "clampToGround", None, QtGui.QApplication.UnicodeUTF8))
        self.altitudemode.setItemText(2, QtGui.QApplication.translate("Form", "relativeToGround", None, QtGui.QApplication.UnicodeUTF8))
        self.KmlColorgroupBox.setTitle(QtGui.QApplication.translate("Form", "Look-At", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Heading", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Tilt", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Latitude", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Longitude", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Range", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Altitude", None, QtGui.QApplication.UnicodeUTF8))
        self.setcamera.setText(QtGui.QApplication.translate("Form", "set", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Form", "Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Heading", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Tilt", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "Latitude", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Form", "Longitude", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Form", "Range", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Form", "Altitude", None, QtGui.QApplication.UnicodeUTF8))
        self.setmodel.setText(QtGui.QApplication.translate("Form", "set", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Model-Position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Form", "Longitude", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Form", "Latitude", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Form", "Altitude", None, QtGui.QApplication.UnicodeUTF8))
        self.setlonlat.setText(QtGui.QApplication.translate("Form", "set", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QtGui.QApplication.translate("Form", "Location", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Form", "Heading", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Form", "Tilt", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Form", "Roll", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QtGui.QApplication.translate("Form", "Orientation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("Form", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("Form", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("Form", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.Xscale.setText(QtGui.QApplication.translate("Form", "1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.Yscale.setText(QtGui.QApplication.translate("Form", "1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.Zscale.setText(QtGui.QApplication.translate("Form", "1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QtGui.QApplication.translate("Form", "Scale", None, QtGui.QApplication.UnicodeUTF8))
        self.save.setText(QtGui.QApplication.translate("Form", "Save", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
