TOPDIR = ..
include $(TOPDIR)/Make/makedefs
include $(TOPDIR)/Make/makedirdefs

DIRS = $(EXAMPLE_DIRS)

include $(TOPDIR)/Make/makedirrules
include $(TOPDIR)/Make/versionrules
include $(TOPDIR)/Make/instrules
include $(TOPDIR)/Make/distrules
include $(TOPDIR)/Make/helprules
