###
# $Id: makefile.vc 9232 2006-07-05 21:42:47Z dburken $
#
# Windows nmake make file.
###
OSSIM_ROOT	=	..\..\..
!INCLUDE $(OSSIM_ROOT)\nmake.opt

OBJ = \
ossimFont.obj \
ossimFontFactoryRegistry.obj \
ossimFreeTypeFont.obj \
ossimFreeTypeFontFactory.obj \
ossimGdBitmapFont.obj

default:	$(OBJ)

clean:
	$(RM) *.obj
