###
# $Id: makefile.vc 16741 2010-02-28 16:02:10Z dburken $
#
# Windows nmake make file.
###
OSSIM_ROOT	=	..\..\..
!INCLUDE $(OSSIM_ROOT)\nmake.opt

OBJ = \
ossimInit.obj

default:	clean $(OBJ)

clean:
	$(RM) *.obj
